version: '{build}'
image: Visual Studio 2019

environment:
  BOOST_ROOT: C:\Libraries\boost_1_71_0
  OPENSSL_ROOT_DIR: c:\beam-libs\openssl
  QT5_ROOT_DIR: C:\Qt\5.15\msvc2019_64
  QML_IMPORT_PATH: $(QT5_ROOT_DIR)\qml
  BUILD_SERVER:
    secure: 5oPcbgETrXo4nmgoqILqgzdjyghCp4tEsBR4gzpEall4E9Vy77ArnCHSRjtLIEai  
  BUILD_CONFIG: RelWithDebInfo
  PATH: $(QT5_ROOT_DIR)\bin;$(PATH)
 
before_build:
  - cmd: git submodule update --init --recursive --remote --jobs 4
  - cmd: cd beam
  - cmd: git apply 3rdparty/protobuf-patch.diff
  - cmd: cd ..
  - cmd: echo %QML_IMPORT_PATH%
  - cmd: git clone --depth=1 https://github.com/BeamMW/libs.git c:/beam-libs
  - cmd: cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=%BUILD_CONFIG% -DBEAM_LINK_TYPE=Static -DBEAM_DEPLOY=True -DBRANCH_NAME=%APPVEYOR_REPO_BRANCH% -DBEAM_HW_WALLET=Off .

test_script:
  - cmd: ctest -C %BUILD_CONFIG% --verbose

build_script:
  - cmake --build . --parallel --config %BUILD_CONFIG%

after_build:
- ps: $env:DATE=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('yyyy.MM.dd')
- ps: $env:TIME=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('HH:mm:ss')
- cmd: >-
    cpack --verbose -G NSIS -C %BUILD_CONFIG%
    
    set /p BEAM_VERSION=<beam_version.gen

    echo BEAM_VERSION = %BEAM_VERSION%

    del beam_version.gen
    
    mkdir pdb
    
    7z a c:/projects/beam-ui/beam/beam-pdb-%BEAM_VERSION%.zip "c:/projects/beam-ui/ui/%BUILD_CONFIG%/Beam Wallet.pdb"

    copy c:\projects\beam-ui\beam\beam-pdb-%BEAM_VERSION%.zip c:\projects\beam-ui\pdb\beam-pdb-%BEAM_VERSION%.zip

    copy c:\projects\beam-ui\BeamWallet-%BEAM_VERSION%-win64.exe c:\projects\beam-ui\Beam-Wallet-%BEAM_VERSION%.exe

on_success:
- ps: $env:DATE=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('yyyy.MM.dd')
- ps: $env:TIME=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('HH:mm:ss')
- cmd: >-
    set BUILDS_SERVER_PATH=%BUILD_SERVER%/%APPVEYOR_REPO_BRANCH%/%DATE%/Release/win
              
    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam-ui/BeamWallet-%BEAM_VERSION%-win64.exe" "%BUILDS_SERVER_PATH%/Beam-Wallet-%BEAM_VERSION%.exe"

    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam-ui/beam/beam-pdb-%BEAM_VERSION%.zip" "%BUILDS_SERVER_PATH%/pdb/beam-pdb-%BEAM_VERSION%.zip"

artifacts:

  - path: pdb/beam-pdb-%BEAM_VERSION%.zip
    name: BeamPdb

  - path: Beam-Wallet-%BEAM_VERSION%.exe
    name: BeamWallet

deploy:
  provider: S3
  access_key_id:
    secure: vku9qEnfo8NirxsplNRBBezWqJa1sV5eSfpt2syfwwk=
  secret_access_key:
    secure: sBTxw2gzbkQrPyMDF5OihFJ+s96yDgNgqbF1/MNmWpYMKrZwkOzIeExfW4Cp3F8B
  bucket: builds.beam.mw
  region: us-west-2
  unzip: false
  set_public: true
  folder: "%APPVEYOR_REPO_BRANCH%/%DATE%/Release/win/"
  artifact: BeamPdb, BeamWallet

notifications:
  - provider: Email
    to:
      - big.romanov@gmail.com
